### ISSUE TITLE
Enhance Azure Pipelines configuration

### ISSUE THREAD

**Issue by Gelio** [mpsujek/codewarssolutions#35]
I have a few enhancements for you to implement in `azure-pipelines.yml` 🙂 

1. Running pipelinese not only on `master`, but on every branch.

    This way when you submit a PR, the CI will run. Currenty, I'm pretty sure it would not run.

2. Split the `npm install and linter` task into 2 tasks: `npm install` and `lint`.

    The more granularity, the better. If it fails you want to know immediately whether the `install` step failed or the `lint` step failed. Currently, the whole step will fail and you will have to immediately dive into the logs to see what's wrong 🙂

**Comment by mpsujek** [comment]
I think it's done now.

**Comment by Gelio** [comment]
Point 2 is done

Point 1 needs to be still addressed 😄 Try to create a branch, push it, create an MR and see if it works. If not, fix it 🙂 If yes, paste the link to the MR

**Comment by mpsujek** [comment]
Point 1 it's working https://github.com/mpsujek/codewarssolutions/pull/36

**Comment by Gelio** [comment]
Nice 👍 I'll close the issue, you can close the MR 🙂
